#!/bin/bash

# echo $1
# echo $2

# echo "Total arguments : $#"
# echo "1st Argument = $1"
# echo "2nd argument = $2"

 
echo "Enter your first number: "
read x
echo "Enter your second number: "
read y

(( sum= x + y ))
echo "The result of addition= $sum"
